[tool.poetry]
name = "cooking-notebook"
version = "0.1.0"
description = ""
authors = ["Aleksey <keepintine@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
pyyaml = "^6.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
